### api http 성공
GET localhost:8080/api/members/11

### api http 실패
GET localhost:8080/api/members/ex
Content-Type: application/json
Accept: application/json

### api 스프링 부트에서 제공하는 BasicErrorController 에서 사용되는 error() 메소드
GET localhost:8080/api/members/ex

###
GET localhost:8080/api/members/bad

###
GET localhost:8080/api/members/user-ex
Accept: application/json

###
GET localhost:8080/api/response-status-ex1

###
GET localhost:8080/api/response-status-ex2

###
GET localhost:8080/api/default-handler-ex?data=ssss